# Generated by Django 2.0.5 on 2020-05-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='counties',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='county',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='county',
            name='cty_code',
        ),
        migrations.RemoveField(
            model_name='county',
            name='dis',
        ),
    ]
